version: '3.9'
services:
  admin:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - '3000:3000'
  server:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - '4000:4000'
